baseURL = 'https://albertomoyano.github.io/blog-gbtexpublisher/'
title = 'gbTeXpublisher'
theme = "hugo-texify2"
publishDir = "docs"
paginate = 4
languageCode = "es"
DefaultContentLanguage = "es"

[params.commentEngine]
code = """
<script src="https://giscus.app/client.js"
        data-repo="albertomoyano/blog-gbtexpublisher"
        data-repo-id="R_kgDOKKd0Qg"
        data-category-id="DIC_kwDOKKd0Qs4CYzSf"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="preferred_color_scheme"
        data-lang="es"
        crossorigin="anonymous"
        async>
</script>
"""

